### ISSUE TITLE
Data import tab

### ISSUE THREAD

**Issue by richardangell** [richardangell/ladybird-umbrella#1]
First tab should allow the user to select data.frame to use in app from R session. 
Subsequent tabs are the generated from the variables in the dataset.
Determine ordered or nominal for each column.

**Comment by michellymenezes** [comment]
The data.frame that the user willl select should be some library provided by R or a selected .csv local file?

**Comment by richardangell** [comment]
I'd like the user to have the data.frame in the R session, then run the app from that R session and use the data.frame from there.

**Comment by richardangell** [comment]
For an initial version it will be easier to have 2 tabs; 
1. data import
2. variable summary plot

within the 2nd tab having a drop down to select the variable to display
