### ISSUE TITLE
Display table of values used in summary plots

### ISSUE THREAD

**Issue by richardangell** [richardangell/ladybird-umbrella#10]
Summarise variables as in issue #5. Display table of (plotted) values alongside plots.

**Comment by michellymenezes** [comment]
Hey, I can help you out in many issues. Can you provide some description with more details about them?
You can see [here](https://michelly.shinyapps.io/as_supercontratadas/) something I've done before.

**Comment by richardangell** [comment]
Hi, thanks for the offer! I'll flesh out the descriptions. Nice app by the way!

**Comment by richardangell** [comment]
Added functionality to display table of summary values in summary graph tab; [2136889](https://github.com/richardangell/ladybird-umbrella/commit/2136889f265b1add270c68973b818e4696e9bc18)
